name: Create Git tag from Python packages

on:
  workflow_call:
    inputs:
      tag_prefix:
        description: Prefix of the tag
        type: string

jobs:
  tag-from-version:
    name: Create Git tag from Python package version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade build

      - name: New tag
        id: new_tag
        run: echo "::set-output name=tag::$(python -c "from build.util import project_wheel_metadata; metadata=project_wheel_metadata('.'); print('/${{ inputs.tag_prefix }}'+metadata['version']);")"

      - name: Latest tag
        id: latest_tag
        run: echo "::set-output name=tag::$(git describe --abbrev=0 --tags)"

      - name: Create tag
        if: ${{ steps.new_tag.outputs.tag != steps.latest_tag.outputs.tag }}
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.new_tag.outputs.tag }}",
              sha: context.sha
            })
