name: Create Git tag from Python packages

on:
  workflow_call:
    inputs:
      tag_prefix:
        description: Prefix of the tag
        type: string

jobs:
  tag-from-version:
    name: Create Git tag from Python package version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade build

      - name: Pckage version
        id: package_version
        run: echo "::set-output name=version::$(python -c 'from build.util import project_wheel_metadata; metadata=project_wheel_metadata(\'.\'); print(metadata[\'version\']):')"

      - name: Latest tag
        id: latest_tag
        run: echo "::set-output name=tag::$(git describe --abbrev=0 --tags)"

      - name: Create tag
        if: ${{ steps.package_version.outputs.version != steps.latest_tag.outputs.tag }}
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN  }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ inputs.tag_prefix }}${{ steps.package_version.outputs.version }}",
              sha: context.sha
            })
