name: Publish Release

on:
  push:
    tags:
      - "*"

jobs:
  release-on-github:
    name: Release package on Github
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get version from tag
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/}

      - name: Set package version
        run: sed "s/version='.*'/version='${{ steps.get_version.outputs.version }}'/" setup.py

      - name: Release package on Github
        uses: malnvenshorn/Python-HelloWorld/publish-python-packages-on-github@master
        with:
          checkout: false
          asset_name: package.tar.gz
