name: Publish Release

on:
  push:
    tags:
      - '*'

jobs:
  release-on-github:
    name: Release package on Github
    uses: malnvenshorn/Python-HelloWorld/.github/workflows/publish-python-packages-on-github.yaml@master
