name: Publish Release

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    name: Build and release package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install pypa/build package
        run: >-
          python -m
          pip install --user build
      - name: Build source tarball
        run: >-
          python -m
          build
          --sdist
          --outdir dist/
      - name: Get package name
        id: package
        run: echo "::set-output name=fullname::$(python setup.py --fullname)"
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          prerelease: false
          release_name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/${{ steps.package.outputs.fullname }}.tar.gz
          asset_name: plugin.tar.gz
          asset_content_type: application/gzip
